// Code generated by MockGen. DO NOT EDIT.
// Source: order_status_fetcher.go
//
// Generated by this command:
//
//	mockgen -source=order_status_fetcher.go -destination=./mock_order_status_fetcher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/iubondar/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderStatusFetcher is a mock of OrderStatusFetcher interface.
type MockOrderStatusFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStatusFetcherMockRecorder
	isgomock struct{}
}

// MockOrderStatusFetcherMockRecorder is the mock recorder for MockOrderStatusFetcher.
type MockOrderStatusFetcherMockRecorder struct {
	mock *MockOrderStatusFetcher
}

// NewMockOrderStatusFetcher creates a new mock instance.
func NewMockOrderStatusFetcher(ctrl *gomock.Controller) *MockOrderStatusFetcher {
	mock := &MockOrderStatusFetcher{ctrl: ctrl}
	mock.recorder = &MockOrderStatusFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStatusFetcher) EXPECT() *MockOrderStatusFetcherMockRecorder {
	return m.recorder
}

// FetchOrderStatus mocks base method.
func (m *MockOrderStatusFetcher) FetchOrderStatus(ctx context.Context, order models.Order) (models.OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrderStatus", ctx, order)
	ret0, _ := ret[0].(models.OrderStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrderStatus indicates an expected call of FetchOrderStatus.
func (mr *MockOrderStatusFetcherMockRecorder) FetchOrderStatus(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrderStatus", reflect.TypeOf((*MockOrderStatusFetcher)(nil).FetchOrderStatus), ctx, order)
}
