// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/register.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/register.go -destination=internal/handler/mocks/mock_user_registrar.go -package=mocks UserRegistrar
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRegistrar is a mock of UserRegistrar interface.
type MockUserRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockUserRegistrarMockRecorder
	isgomock struct{}
}

// MockUserRegistrarMockRecorder is the mock recorder for MockUserRegistrar.
type MockUserRegistrarMockRecorder struct {
	mock *MockUserRegistrar
}

// NewMockUserRegistrar creates a new mock instance.
func NewMockUserRegistrar(ctrl *gomock.Controller) *MockUserRegistrar {
	mock := &MockUserRegistrar{ctrl: ctrl}
	mock.recorder = &MockUserRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRegistrar) EXPECT() *MockUserRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockUserRegistrar) Register(ctx context.Context, userID uuid.UUID, login, passwordHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, userID, login, passwordHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserRegistrarMockRecorder) Register(ctx, userID, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRegistrar)(nil).Register), ctx, userID, login, passwordHash)
}
