// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/register_order.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/register_order.go -destination=internal/handler/mocks/order_registrar.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	constants "github.com/iubondar/gophermart/internal/constants"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRegistrar is a mock of OrderRegistrar interface.
type MockOrderRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRegistrarMockRecorder
	isgomock struct{}
}

// MockOrderRegistrarMockRecorder is the mock recorder for MockOrderRegistrar.
type MockOrderRegistrarMockRecorder struct {
	mock *MockOrderRegistrar
}

// NewMockOrderRegistrar creates a new mock instance.
func NewMockOrderRegistrar(ctrl *gomock.Controller) *MockOrderRegistrar {
	mock := &MockOrderRegistrar{ctrl: ctrl}
	mock.recorder = &MockOrderRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRegistrar) EXPECT() *MockOrderRegistrarMockRecorder {
	return m.recorder
}

// RegisterOrder mocks base method.
func (m *MockOrderRegistrar) RegisterOrder(ctx context.Context, userID uuid.UUID, orderNumber string) (constants.OrderRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(constants.OrderRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockOrderRegistrarMockRecorder) RegisterOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockOrderRegistrar)(nil).RegisterOrder), ctx, userID, orderNumber)
}
