// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/withdraw.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/withdraw.go -destination=internal/mocks/mock_withdraw.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	constants "github.com/iubondar/gophermart/internal/constants"
	usecase "github.com/iubondar/gophermart/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawUsecase is a mock of WithdrawUsecase interface.
type MockWithdrawUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawUsecaseMockRecorder
	isgomock struct{}
}

// MockWithdrawUsecaseMockRecorder is the mock recorder for MockWithdrawUsecase.
type MockWithdrawUsecaseMockRecorder struct {
	mock *MockWithdrawUsecase
}

// NewMockWithdrawUsecase creates a new mock instance.
func NewMockWithdrawUsecase(ctrl *gomock.Controller) *MockWithdrawUsecase {
	mock := &MockWithdrawUsecase{ctrl: ctrl}
	mock.recorder = &MockWithdrawUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawUsecase) EXPECT() *MockWithdrawUsecaseMockRecorder {
	return m.recorder
}

// Withdraw mocks base method.
func (m *MockWithdrawUsecase) Withdraw(ctx context.Context, userID uuid.UUID, in usecase.WithdrawIn) (constants.WithdrawResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, in)
	ret0, _ := ret[0].(constants.WithdrawResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawUsecaseMockRecorder) Withdraw(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawUsecase)(nil).Withdraw), ctx, userID, in)
}
