// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_balance.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_balance.go -destination=internal/mocks/mock_get_balance_usecase.go -package=mocks GetBalanceUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/iubondar/gophermart/internal/models"
	usecase "github.com/iubondar/gophermart/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// Account mocks base method.
func (m *MockBalanceRepository) Account(ctx context.Context, userID uuid.UUID) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Account", ctx, userID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Account indicates an expected call of Account.
func (mr *MockBalanceRepositoryMockRecorder) Account(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Account", reflect.TypeOf((*MockBalanceRepository)(nil).Account), ctx, userID)
}

// MockGetBalanceUsecase is a mock of GetBalanceUsecase interface.
type MockGetBalanceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetBalanceUsecaseMockRecorder
	isgomock struct{}
}

// MockGetBalanceUsecaseMockRecorder is the mock recorder for MockGetBalanceUsecase.
type MockGetBalanceUsecaseMockRecorder struct {
	mock *MockGetBalanceUsecase
}

// NewMockGetBalanceUsecase creates a new mock instance.
func NewMockGetBalanceUsecase(ctrl *gomock.Controller) *MockGetBalanceUsecase {
	mock := &MockGetBalanceUsecase{ctrl: ctrl}
	mock.recorder = &MockGetBalanceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetBalanceUsecase) EXPECT() *MockGetBalanceUsecaseMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockGetBalanceUsecase) GetBalance(ctx context.Context, userID uuid.UUID) (usecase.BalanceOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(usecase.BalanceOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockGetBalanceUsecaseMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockGetBalanceUsecase)(nil).GetBalance), ctx, userID)
}
