// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/orders.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/orders.go -destination=internal/mocks/mock_orders_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	usecase "github.com/iubondar/gophermart/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersUsecase is a mock of OrdersUsecase interface.
type MockOrdersUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersUsecaseMockRecorder
	isgomock struct{}
}

// MockOrdersUsecaseMockRecorder is the mock recorder for MockOrdersUsecase.
type MockOrdersUsecaseMockRecorder struct {
	mock *MockOrdersUsecase
}

// NewMockOrdersUsecase creates a new mock instance.
func NewMockOrdersUsecase(ctrl *gomock.Controller) *MockOrdersUsecase {
	mock := &MockOrdersUsecase{ctrl: ctrl}
	mock.recorder = &MockOrdersUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersUsecase) EXPECT() *MockOrdersUsecaseMockRecorder {
	return m.recorder
}

// GetOrders mocks base method.
func (m *MockOrdersUsecase) GetOrders(ctx context.Context, userID uuid.UUID) ([]usecase.OrdersOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]usecase.OrdersOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrdersUsecaseMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrdersUsecase)(nil).GetOrders), ctx, userID)
}
