// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/withdraw.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/withdraw.go -destination=internal/handler/mocks/mock_withdrawer.go -package=mocks Withdrawer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	constants "github.com/iubondar/gophermart/internal/constants"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawer is a mock of Withdrawer interface.
type MockWithdrawer struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawerMockRecorder
	isgomock struct{}
}

// MockWithdrawerMockRecorder is the mock recorder for MockWithdrawer.
type MockWithdrawerMockRecorder struct {
	mock *MockWithdrawer
}

// NewMockWithdrawer creates a new mock instance.
func NewMockWithdrawer(ctrl *gomock.Controller) *MockWithdrawer {
	mock := &MockWithdrawer{ctrl: ctrl}
	mock.recorder = &MockWithdrawerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawer) EXPECT() *MockWithdrawerMockRecorder {
	return m.recorder
}

// Withdraw mocks base method.
func (m *MockWithdrawer) Withdraw(ctx context.Context, userID uuid.UUID, orderNumber string, sum float32) (constants.WithdrawResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderNumber, sum)
	ret0, _ := ret[0].(constants.WithdrawResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawerMockRecorder) Withdraw(ctx, userID, orderNumber, sum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawer)(nil).Withdraw), ctx, userID, orderNumber, sum)
}
