// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/register_order.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/register_order.go -destination=internal/mocks/register_order_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	constants "github.com/iubondar/gophermart/internal/constants"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// RegisterOrder mocks base method.
func (m *MockOrderRepository) RegisterOrder(ctx context.Context, userID uuid.UUID, orderNumber string) (constants.OrderRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(constants.OrderRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockOrderRepositoryMockRecorder) RegisterOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockOrderRepository)(nil).RegisterOrder), ctx, userID, orderNumber)
}

// MockRegisterOrderUsecase is a mock of RegisterOrderUsecase interface.
type MockRegisterOrderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterOrderUsecaseMockRecorder
	isgomock struct{}
}

// MockRegisterOrderUsecaseMockRecorder is the mock recorder for MockRegisterOrderUsecase.
type MockRegisterOrderUsecaseMockRecorder struct {
	mock *MockRegisterOrderUsecase
}

// NewMockRegisterOrderUsecase creates a new mock instance.
func NewMockRegisterOrderUsecase(ctrl *gomock.Controller) *MockRegisterOrderUsecase {
	mock := &MockRegisterOrderUsecase{ctrl: ctrl}
	mock.recorder = &MockRegisterOrderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterOrderUsecase) EXPECT() *MockRegisterOrderUsecaseMockRecorder {
	return m.recorder
}

// RegisterOrder mocks base method.
func (m *MockRegisterOrderUsecase) RegisterOrder(ctx context.Context, userID uuid.UUID, orderNumber string) (constants.OrderRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", ctx, userID, orderNumber)
	ret0, _ := ret[0].(constants.OrderRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockRegisterOrderUsecaseMockRecorder) RegisterOrder(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockRegisterOrderUsecase)(nil).RegisterOrder), ctx, userID, orderNumber)
}
