// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/withdrawals.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/withdrawals.go -destination=internal/mocks/withdrawals_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/iubondar/gophermart/internal/models"
	usecase "github.com/iubondar/gophermart/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalsRepository is a mock of WithdrawalsRepository interface.
type MockWithdrawalsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsRepositoryMockRecorder
	isgomock struct{}
}

// MockWithdrawalsRepositoryMockRecorder is the mock recorder for MockWithdrawalsRepository.
type MockWithdrawalsRepositoryMockRecorder struct {
	mock *MockWithdrawalsRepository
}

// NewMockWithdrawalsRepository creates a new mock instance.
func NewMockWithdrawalsRepository(ctrl *gomock.Controller) *MockWithdrawalsRepository {
	mock := &MockWithdrawalsRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsRepository) EXPECT() *MockWithdrawalsRepositoryMockRecorder {
	return m.recorder
}

// Withdrawals mocks base method.
func (m *MockWithdrawalsRepository) Withdrawals(ctx context.Context, userID uuid.UUID) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawals", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawals indicates an expected call of Withdrawals.
func (mr *MockWithdrawalsRepositoryMockRecorder) Withdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawals", reflect.TypeOf((*MockWithdrawalsRepository)(nil).Withdrawals), ctx, userID)
}

// MockWithdrawalsUsecase is a mock of WithdrawalsUsecase interface.
type MockWithdrawalsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsUsecaseMockRecorder
	isgomock struct{}
}

// MockWithdrawalsUsecaseMockRecorder is the mock recorder for MockWithdrawalsUsecase.
type MockWithdrawalsUsecaseMockRecorder struct {
	mock *MockWithdrawalsUsecase
}

// NewMockWithdrawalsUsecase creates a new mock instance.
func NewMockWithdrawalsUsecase(ctrl *gomock.Controller) *MockWithdrawalsUsecase {
	mock := &MockWithdrawalsUsecase{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsUsecase) EXPECT() *MockWithdrawalsUsecaseMockRecorder {
	return m.recorder
}

// GetWithdrawals mocks base method.
func (m *MockWithdrawalsUsecase) GetWithdrawals(ctx context.Context, userID uuid.UUID) ([]usecase.WithdrawalOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]usecase.WithdrawalOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockWithdrawalsUsecaseMockRecorder) GetWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockWithdrawalsUsecase)(nil).GetWithdrawals), ctx, userID)
}
