// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/login.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginChecker is a mock of LoginChecker interface.
type MockLoginChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLoginCheckerMockRecorder
}

// MockLoginCheckerMockRecorder is the mock recorder for MockLoginChecker.
type MockLoginCheckerMockRecorder struct {
	mock *MockLoginChecker
}

// NewMockLoginChecker creates a new mock instance.
func NewMockLoginChecker(ctrl *gomock.Controller) *MockLoginChecker {
	mock := &MockLoginChecker{ctrl: ctrl}
	mock.recorder = &MockLoginCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginChecker) EXPECT() *MockLoginCheckerMockRecorder {
	return m.recorder
}

// CheckLogin mocks base method.
func (m *MockLoginChecker) CheckLogin(ctx context.Context, login, passwordHash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLogin", ctx, login, passwordHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLogin indicates an expected call of CheckLogin.
func (mr *MockLoginCheckerMockRecorder) CheckLogin(ctx, login, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLogin", reflect.TypeOf((*MockLoginChecker)(nil).CheckLogin), ctx, login, passwordHash)
} 